#   █████╗ ██╗      █████╗  ██████╗██████╗ ██╗████████╗████████╗██╗   ██╗
#  ██╔══██╗██║     ██╔══██╗██╔════╝██╔══██╗██║╚══██╔══╝╚══██╔══╝╚██╗ ██╔╝
#  ███████║██║     ███████║██║     ██████╔╝██║   ██║      ██║    ╚████╔╝
#  ██╔══██║██║     ██╔══██║██║     ██╔══██╗██║   ██║      ██║     ╚██╔╝
#  ██║  ██║███████╗██║  ██║╚██████╗██║  ██║██║   ██║      ██║      ██║
#  ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚═╝   ╚═╝      ╚═╝      ╚═╝
#	gh0stzk - https://github.com/gh0stzk/dotfiles

[general]
import = ["~/.config/alacritty/rice-colors.toml", "~/.config/alacritty/fonts.toml"]
live_config_reload = true

[cursor]
blink_interval = 350
unfocused_hollow = false
thickness = 0.5

[cursor.style]
blinking = "On"
shape = "Block"

[selection]
save_to_clipboard = true

[window]
#decorations = "none"
title = "~"
dynamic_title = false
opacity = 0.9788
#dynamic_padding = false

#[window.padding]
#x = 2
#y = 2

#[scrolling]
#history = 10000
#multiplier = 3

#[bell]
#animation = "Linear"
#duration = 0
#command = { program = "paplay", args = ["/usr/share/sounds/freedesktop/stereo/dialog-error.oga"] }
